[theme]
base = "light"
primaryColor = "#5865F2"
backgroundColor = "#E0E3FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
